### ISSUE TITLE
Tool not showing up

### ISSUE THREAD

**Issue by AKA-SLY** [SietseB/GP-Tool-Wheel#2] opened 2024-09-15 20:04 UTC
Hi, im trying to use F8 or any shortcut, but wheel wont show up. Blender 4.2 LTS

Thanks

**Comment by SietseB** [comment] 2024-09-16 20:25
That's unfortunate, of course. Two basic checks:
1. You have a Grease Pencil object selected? The wheel won't show when something else is active (mesh, camera etc.).
2. The mouse pointer is somewhere in the 3D Viewport area when you hit F8?

Otherwise I need a bit more information to figure this one out:
- Which operating system (Windows, Linux, macOS)?
- Can you see an error in the system console (on Windows see menu item `Window` | `Toggle System Console`)?
- Any add-ons installed that could interfere with GP Tool Wheel?

**Comment by SietseB** [comment] 2024-11-01 09:22
Without more information, it's hard to figure out what the problem is. So I'm closing this issue for now.

**Comment by SietseB** [comment] 2024-11-01 09:23
Without more information, it's hard to figure out what the problem is. So I'm closing this issue for now.

**Closed by SietseB** 2024-11-01 09:23 UTC
